CREATE TABLE IF NOT EXISTS user
(
    UserId INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(255) UNIQUE NOT NULL,
    Email VARCHAR(255) NOT NULL,
    PasswordHash VARCHAR(255),
    OTP VARCHAR(255),
    LastLogin TIMESTAMP,
    PasswordResetCode VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_role
(
    UserRoleId INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_user_roles
(
    UserId INT NOT NULL,
    UserRoleId INT NOT NULL,
    PRIMARY KEY (UserId, UserRoleId),
    FOREIGN KEY (UserId) REFERENCES user(UserId),
    FOREIGN KEY (UserRoleId) REFERENCES user_role(UserRoleId)
);
